library(naniar)
library(dplyr)

dane <- read.csv("Hipoteczny.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)

# Zamiana pustych wartości na NA
dane <- dane %>%
  mutate(Gender = ifelse(Gender == "" | Gender == "NULL" | Gender == "N/A", NA, Gender)) %>%
  mutate(Married = ifelse(Married == "" | Married == "NULL" | Married == "N/A", NA, Married)) %>%
  mutate(Dependents = ifelse(Dependents == "" | Dependents == "NULL" | Dependents == "N/A", NA, Dependents)) %>%
  mutate(Education = ifelse(Education == "" | Education == "NULL" | Education == "N/A", NA, Education)) %>%
  mutate(Self_Employed = ifelse(Self_Employed == "" | Self_Employed == "NULL" | Self_Employed == "N/A", NA, Self_Employed)) %>%
  mutate(ApplicantIncome = ifelse(ApplicantIncome == "" | ApplicantIncome == "NULL" | ApplicantIncome == "N/A", NA, ApplicantIncome)) %>%
  mutate(CoapplicantIncome = ifelse(CoapplicantIncome == "" | CoapplicantIncome == "NULL" | CoapplicantIncome == "N/A", NA, CoapplicantIncome)) %>%
  mutate(LoanAmount = ifelse(LoanAmount == "" | LoanAmount == "NULL" | LoanAmount == "N/A", NA, LoanAmount)) %>%
  mutate(Loan_Amount_Term = ifelse(Loan_Amount_Term == "" | Loan_Amount_Term == "NULL" | Loan_Amount_Term == "N/A", NA, Loan_Amount_Term)) %>%
  mutate(Credit_History = ifelse(Credit_History == "" | Credit_History == "NULL" | Credit_History == "N/A", NA, Credit_History)) %>%
  mutate(Property_Area = ifelse(Property_Area== "" | Property_Area == "NULL" | Property_Area == "N/A", NA, Property_Area))

#Utworzenie tabeli podsumowującej braki w tabeli 
miss_var_summary(dane)

#Braki są zauważalne jedynie w: Credit_History, Self_Employed, Gender, Dependents, Loan_Amount_Term, LoanAmount

#Utowrzenie tabel podsumowujących według poszczególnych kategori
dane %>%
  group_by(Married) %>%
    miss_var_summary() %>%
    print(n=22)
    
dane %>%
  group_by(Self_Employed) %>%
    miss_var_summary() %>%
    print(n=33)

dane %>%
  group_by(LoanAmount) %>%
    miss_var_summary() %>%
    print(n=10)

dane %>%
  group_by(Property_Area) %>%
    miss_var_summary() %>%
    print(n=33)
 
 dane %>%
  group_by(Gender) %>%
    miss_var_summary() %>%
    print(n=33)
    
dane %>%
  group_by(Education) %>%
    miss_var_summary() %>%
    print(n=22)

dane %>%
  group_by(CoapplicantIncome) %>%
    miss_var_summary() %>%
    print(n=10)

dane %>%
  group_by(Credit_History) %>%
    miss_var_summary() %>%
    print(n=33)
 
 
#Tabela podsumowująca brakujące wartości według wiersza    
dane %>%
  miss_case_table()
 
#Wizualizacjia brakujących danych 
vis_miss(dane)


#Wizualizacjia brakujących zmiennych, według poszczególnych wierszy
gg_miss_fct(dane, fct = Married)
gg_miss_fct(dane, fct = Self_Employed)
gg_miss_fct(dane, fct = LoanAmount)
gg_miss_fct(dane, fct = Property_Area)
  
gg_miss_fct(dane, fct = Gender)
gg_miss_fct(dane, fct = Education)
gg_miss_fct(dane, fct = CoapplicantIncome)
gg_miss_fct(dane, fct = Credit_History)  
  
  
#Wizualizacja jak często braki współwystępują między zmiennymi 
#(1 wiersz braku w Credit_History i Loan_Amount_Team)
gg_miss_upset(dane, 
              nsets = 6)
#najwięcej brakuje danych w credit history
library(VIM)
data <-hotdeck(dane)
miss_var_summary(data)


#analiza danych odstających 
# Tworzenie histogramów
hist(
  data$LoanAmount,
  main = "Histogram wartości LoanAmount",
  xlab = "Kwota pożyczki",
  ylab = "Częstość",
  col = "lightblue",
  border = "black",
  breaks = 20 # Możesz dostosować liczbę przedziałów
)

hist(
  data$ApplicantIncome,
  main = "Histogram dla ApplicantIncome",
  xlab = "Dochód wnioskodawcy",
  ylab = "Częstość",
  col = "lightblue",
  border = "black",
  breaks = 20 
)

hist(
  data$CoapplicantIncome,
  main = "Histogram dla CoapplicantIncome",
  xlab = "Dochód współwnioskodawcy",
  ylab = "Częstość",
  col = "lightblue",
  border = "black",
  breaks = 20 
)

hist(
  data$LoanAmount,
  main = "Histogram dla LoanAmount",
  xlab = "Kwota pożyczki",
  ylab = "Częstość",
  col = "lightblue",
  border = "black",
  breaks = 20 
)

hist(
  data$Loan_Amount_Term,
  main = "Histogram dla Loan_Amount_Term",
  xlab = "Termin kwoty pożyczki",
  ylab = "Częstość",
  col = "lightblue",
  border = "black",
  breaks = 20 
)
hist(
  data$Credit_History,
  main = "Histogram dla Credit_History",
  xlab = "Historia Kredytu",
  ylab = "Częstość",
  col = "lightblue",
  border = "black",
  breaks = 20 
)

#Wykresy pudełkowe dla kluczowych zmiennych
#Identyfikujemy dane odtające i porównujemy rozkłady między grupami
boxplot(
  data$LoanAmount,
  main = "Wykres pudełkowy dla LoanAmount",
  ylab = "Kwota pożyczki",
  col = "lightblue",
  border = "black"
)
#szukamy odstających punktów
outliers <- boxplot.stats(dane$LoanAmount)$out
print(outliers)

# dane [1] wykazują duże odchylenia w stosunku do reszty danych
#czy powinnyśmy je usunąć?

boxplot(
  data$ApplicantIncome,
  main = "Wykres pudełkowy dla ApplicantIncome",
  ylab = "Dochód wnioskodawcy",
  col = "lightgreen",
  border = "black"
)

boxplot(
  data$CoapplicantIncome,
  main = "Wykres pudełkowy dla CoapplicantIncome",
  ylab = "Dochód współwnioskodawcy",
  col = "lightpink",
  border = "black"
)

boxplot(
  data$Loan_Amount_Term,
  main = "Wykres pudełkowy dla Loan_Amount_Term",
  ylab = "Termin pożyczki",
  col = "pink",
  border = "black"
)

#porównanie grup
boxplot(
  LoanAmount ~ Married,
  data = data,
  main = "Wykres pudełkowy LoanAmount względem Married",
  xlab = "Stan cywilny",
  ylab = "Kwota pożyczki",
  col = c("lightblue", "lightgreen"),
  border = "black"
)

boxplot(
  ApplicantIncome ~ Education,
  data = data,
  main = "Wykres pudełkowy ApplicantIncome względem Education",
  xlab = "Wykształcenie",
  ylab = "Dochód wnioskodawcy",
  col = c("lightblue", "lightpink"),
  border = "black"
)

library(ggplot2)

ggplot(data, aes(x=Education,y=LoanAmount))+
  geom_boxplot() +
  labs(title="Wysokość pożyczki wg wykształcenia", x="Wykształcenie", y="Wysokość pożyczki") +
  theme_bw() + #typ kolorystyczny wykresu
  facet_wrap(~Gender) +
  coord_flip() #obraca wykres
  

# Wykresy słupkowe skumulowane. Pokazanie związku między Credit_History a resztą danych chr
ggplot(data, aes(x = Education, fill = factor(Credit_History))) +
  geom_bar(position = "fill") +
  labs(y = "Proporcja", fill = "Credit History") +
  theme_minimal()
  
ggplot(data, aes(x = Gender, fill = factor(Credit_History))) +
  geom_bar(position = "fill") +
  labs(y = "Proporcja", fill = "Credit History") +
  theme_minimal()
  
ggplot(data, aes(x = Married, fill = factor(Credit_History))) +
  geom_bar(position = "fill") +
  labs(y = "Proporcja", fill = "Credit History") +
  theme_minimal()
  
ggplot(data, aes(x = Dependents, fill = factor(Credit_History))) +
  geom_bar(position = "fill") +
  labs(y = "Proporcja", fill = "Credit History") +
  theme_minimal()
  
ggplot(data, aes(x = Self_Employed, fill = factor(Credit_History))) +
  geom_bar(position = "fill") +
  labs(y = "Proporcja", fill = "Credit History") +
  theme_minimal()
  
ggplot(data, aes(x = Property_Area, fill = factor(Credit_History))) +
  geom_bar(position = "fill") +
  labs(y = "Proporcja", fill = "Credit History") +
  theme_minimal()





